version: 1

models:

  - name: mutations
    columns:
      - name: idg
        data_tests:
          - unique
          - not_null

  - name: classes
    columns:
      - name: idg
        data_tests:
          - not_null