version: 1

models:
  - name: classes
    columns:
      - name: idg
        data_tests:
          - not_null

      - name: libelle
        data_tests:
          - not_null

      - name: surface
        data_tests:
          - not_null
          - strict_positive